language: go
go: 1.13.8
services:
  - docker
deploy:
  provider: gae
  keyfile: fitnessdiary-06b50b2c17eb.json
  project: fitnessdiary
before_install:
  - openssl aes-256-cbc -K $encrypted_42bf725d37a2_key -iv $encrypted_42bf725d37a2_iv
    -in fitnessdiary-06b50b2c17eb.json.enc -out fitnessdiary-06b50b2c17eb.json -d
