sudo: true
language: go
go: 1.12.7
deploy:
  provider: gae
  keyfile: fitnessdiary-269117-d3d5338fdf56.json
  project: fitnessdiary-269117
  default: true
  on:
    all_branches: true
before_install:
  - openssl aes-256-cbc -K $encrypted_42bf725d37a2_key -iv $encrypted_42bf725d37a2_iv
    -in fitnessdiary-269117-d3d5338fdf56.json.enc -out fitnessdiary-269117-d3d5338fdf56.json
    -d
