sudo: true

language: go

go: 1.12.7

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: fitnessdiary-06b50b2c17eb.json
  project: fitnessdiary
  on:
    all_branches: true

before_install:
  - openssl aes-256-cbc -K $encrypted_42bf725d37a2_key -iv $encrypted_42bf725d37a2_iv
    -in fitnessdiary-06b50b2c17eb.json.enc -out fitnessdiary-06b50b2c17eb.json -d
  - GO111MODULE: off